SET(CMAKE_SYSTEM_NAME Windows)
SET(CMAKE_INSTALL_PREFIX /usr)
SET(TOOLCHAIN_PREFIX x86_64-w64-mingw32)
SET(BIN_DIR ${CMAKE_INSTALL_PREFIX}/bin)

SET(CMAKE_C_COMPILER       ${BIN_DIR}/${TOOLCHAIN_PREFIX}-gcc )
SET(CMAKE_CXX_COMPILER     ${BIN_DIR}/${TOOLCHAIN_PREFIX}-g++ )
SET(CMAKE_RC_COMPILER      ${BIN_DIR}/${TOOLCHAIN_PREFIX}-windres )
SET(CMAKE_ASM-ATT_COMPILER ${BIN_DIR}/${TOOLCHAIN_PREFIX}-as )

SET(CMAKE_FIND_ROOT_PATH ${CMAKE_INSTALL_PREFIX}/${TOOLCHAIN_PREFIX} )

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
